{
  "base": "{{ mode }}",
  "spaces": {
    "back": "{{ background }}",
    "title": "{{ foreground }}",
    "text": "{{ foreground }}",
    "text_hi": "{{ bright_foreground }}",
    "header": "{{ dark_background }}",
    "header_text": "{{ foreground }}",
    "header_text_hi": "{{ bright_foreground }}"
  },
  "colors": {
    "user_interface.editor_border": "{{ darker_background }}",
    "user_interface.widget_text_cursor": "{{ accent }}",
    "user_interface.link": "{{ accent }}",
    "user_interface.panel_header": "{{ lighter_background }}",
    "user_interface.panel_back": "{{ lighter_background }}",
    "user_interface.panel_title": "{{ foreground }}",
    "user_interface.panel_text": "{{ foreground }}",
    "user_interface.panel_active": "{{ accent }}",
    "user_interface.axis_x": "{{ red }}",
    "user_interface.axis_y": "{{ green }}",
    "user_interface.axis_z": "{{ blue }}",
    "user_interface.axis_w": "{{ yellow }}",
    "user_interface.gizmo_primary": "{{ yellow }}",
    "user_interface.gizmo_secondary": "{{ cyan }}",
    "user_interface.gizmo_a": "{{ green }}",
    "user_interface.gizmo_b": "{{ red }}",
    "user_interface.icon_object": "{{ orange }}",
    "user_interface.icon_object_data": "{{ green }}",
    "user_interface.icon_modifier": "{{ blue }}",
    "user_interface.icon_shading": "{{ red }}",
    "user_interface.icon_folder": "{{ yellow }}",
    "user_interface.icon_autokey": "{{ red }}",

    "user_interface.wcol_regular.inner": "{{ mix lighter_background foreground 12% }}",
    "user_interface.wcol_regular.inner_sel": "{{ selection }}",
    "user_interface.wcol_regular.outline": "{{ lighter_background }}",
    "user_interface.wcol_regular.outline_sel": "{{ accent }}",
    "user_interface.wcol_regular.item": "{{ dark_background }}",
    "user_interface.wcol_regular.text": "{{ foreground }}",
    "user_interface.wcol_regular.text_sel": "{{ selection_foreground }}",

    "user_interface.wcol_tool.inner": "{{ mix lighter_background foreground 12% }}",
    "user_interface.wcol_tool.inner_sel": "{{ selection }}",
    "user_interface.wcol_tool.outline": "{{ lighter_background }}",
    "user_interface.wcol_tool.outline_sel": "{{ accent }}",
    "user_interface.wcol_tool.item": "{{ foreground }}",
    "user_interface.wcol_tool.text": "{{ foreground }}",
    "user_interface.wcol_tool.text_sel": "{{ selection_foreground }}",

    "user_interface.wcol_toolbar_item.inner": "{{ lighter_background }}",
    "user_interface.wcol_toolbar_item.inner_sel": "{{ selection }}",
    "user_interface.wcol_toolbar_item.outline": "{{ lighter_background }}",
    "user_interface.wcol_toolbar_item.outline_sel": "{{ accent }}",
    "user_interface.wcol_toolbar_item.item": "{{ foreground }}",
    "user_interface.wcol_toolbar_item.text": "{{ foreground }}",
    "user_interface.wcol_toolbar_item.text_sel": "{{ selection_foreground }}",

    "user_interface.wcol_toggle.inner": "{{ mix lighter_background foreground 12% }}",
    "user_interface.wcol_toggle.inner_sel": "{{ selection }}",
    "user_interface.wcol_toggle.outline": "{{ lighter_background }}",
    "user_interface.wcol_toggle.outline_sel": "{{ accent }}",
    "user_interface.wcol_toggle.text": "{{ foreground }}",
    "user_interface.wcol_toggle.text_sel": "{{ selection_foreground }}",

    "user_interface.wcol_radio.inner": "{{ mix lighter_background foreground 12% }}",
    "user_interface.wcol_radio.inner_sel": "{{ selection }}",
    "user_interface.wcol_radio.outline": "{{ lighter_background }}",
    "user_interface.wcol_radio.outline_sel": "{{ accent }}",
    "user_interface.wcol_radio.text": "{{ foreground }}",
    "user_interface.wcol_radio.text_sel": "{{ selection_foreground }}",

    "user_interface.wcol_option.inner": "{{ mix lighter_background foreground 12% }}",
    "user_interface.wcol_option.inner_sel": "{{ accent }}",
    "user_interface.wcol_option.outline": "{{ lighter_background }}",
    "user_interface.wcol_option.outline_sel": "{{ accent }}",
    "user_interface.wcol_option.item": "{{ background }}",
    "user_interface.wcol_option.text": "{{ foreground }}",
    "user_interface.wcol_option.text_sel": "{{ bright_foreground }}",

    "user_interface.wcol_num.inner": "{{ mix lighter_background foreground 12% }}",
    "user_interface.wcol_num.inner_sel": "{{ selection }}",
    "user_interface.wcol_num.outline": "{{ lighter_background }}",
    "user_interface.wcol_num.outline_sel": "{{ accent }}",
    "user_interface.wcol_num.item": "{{ dark_foreground }}",
    "user_interface.wcol_num.text": "{{ foreground }}",
    "user_interface.wcol_num.text_sel": "{{ selection_foreground }}",

    "user_interface.wcol_numslider.inner": "{{ mix lighter_background foreground 12% }}",
    "user_interface.wcol_numslider.inner_sel": "{{ selection }}",
    "user_interface.wcol_numslider.outline": "{{ lighter_background }}",
    "user_interface.wcol_numslider.outline_sel": "{{ accent }}",
    "user_interface.wcol_numslider.item": "{{ mix lighter_background accent 45% }}",
    "user_interface.wcol_numslider.text": "{{ foreground }}",
    "user_interface.wcol_numslider.text_sel": "{{ selection_foreground }}",

    "user_interface.wcol_text.inner": "{{ dark_background }}",
    "user_interface.wcol_text.inner_sel": "{{ darker_background }}",
    "user_interface.wcol_text.outline": "{{ lighter_background }}",
    "user_interface.wcol_text.outline_sel": "{{ accent }}",
    "user_interface.wcol_text.item": "{{ selection }}",
    "user_interface.wcol_text.text": "{{ foreground }}",
    "user_interface.wcol_text.text_sel": "{{ bright_foreground }}",

    "user_interface.wcol_box.inner": "{{ lighter_background }}",
    "user_interface.wcol_box.inner_sel": "{{ selection }}",
    "user_interface.wcol_box.outline": "{{ lighter_background }}",
    "user_interface.wcol_box.text": "{{ foreground }}",
    "user_interface.wcol_box.text_sel": "{{ selection_foreground }}",

    "user_interface.wcol_pulldown.inner": "{{ lighter_background }}",
    "user_interface.wcol_pulldown.inner_sel": "{{ selection }}",
    "user_interface.wcol_pulldown.text": "{{ foreground }}",
    "user_interface.wcol_pulldown.text_sel": "{{ selection_foreground }}",

    "user_interface.wcol_menu.inner": "{{ mix lighter_background foreground 12% }}",
    "user_interface.wcol_menu.inner_sel": "{{ selection }}",
    "user_interface.wcol_menu.outline": "{{ lighter_background }}",
    "user_interface.wcol_menu.outline_sel": "{{ accent }}",
    "user_interface.wcol_menu.item": "{{ dark_foreground }}",
    "user_interface.wcol_menu.text": "{{ foreground }}",
    "user_interface.wcol_menu.text_sel": "{{ selection_foreground }}",

    "user_interface.wcol_menu_back.inner": "{{ darker_background }}",
    "user_interface.wcol_menu_back.inner_sel": "{{ selection }}",
    "user_interface.wcol_menu_back.outline": "{{ lighter_background }}",
    "user_interface.wcol_menu_back.outline_sel": "{{ lighter_background }}",
    "user_interface.wcol_menu_back.text": "{{ dark_foreground }}",
    "user_interface.wcol_menu_back.text_sel": "{{ selection_foreground }}",

    "user_interface.wcol_menu_item.inner_sel": "{{ selection }}",
    "user_interface.wcol_menu_item.item": "{{ dark_foreground }}",
    "user_interface.wcol_menu_item.text": "{{ foreground }}",
    "user_interface.wcol_menu_item.text_sel": "{{ selection_foreground }}",

    "user_interface.wcol_pie_menu.inner": "{{ darker_background }}",
    "user_interface.wcol_pie_menu.inner_sel": "{{ selection }}",
    "user_interface.wcol_pie_menu.outline": "{{ lighter_background }}",
    "user_interface.wcol_pie_menu.item": "{{ accent }}",
    "user_interface.wcol_pie_menu.text": "{{ foreground }}",
    "user_interface.wcol_pie_menu.text_sel": "{{ selection_foreground }}",

    "user_interface.wcol_tooltip.inner": "{{ darker_background }}",
    "user_interface.wcol_tooltip.outline": "{{ lighter_background }}",
    "user_interface.wcol_tooltip.item": "{{ foreground }}",
    "user_interface.wcol_tooltip.text": "{{ foreground }}",

    "user_interface.wcol_list_item.inner_sel": "{{ selection }}",
    "user_interface.wcol_list_item.outline_sel": "{{ accent }}",
    "user_interface.wcol_list_item.text": "{{ foreground }}",
    "user_interface.wcol_list_item.text_sel": "{{ selection_foreground }}",

    "user_interface.wcol_tab.inner": "{{ dark_background }}",
    "user_interface.wcol_tab.inner_sel": "{{ lighter_background }}",
    "user_interface.wcol_tab.outline": "{{ darker_background }}",
    "user_interface.wcol_tab.outline_sel": "{{ lighter_background }}",
    "user_interface.wcol_tab.text": "{{ dark_foreground }}",
    "user_interface.wcol_tab.text_sel": "{{ foreground }}",

    "user_interface.wcol_scroll.item": "{{ mix lighter_background foreground 25% }}",
    "user_interface.wcol_scroll.outline": "{{ lighter_background }}",
    "user_interface.wcol_progress.item": "{{ accent }}",
    "user_interface.wcol_curve.inner": "{{ dark_background }}",
    "user_interface.wcol_curve.item": "{{ foreground }}",

    "user_interface.wcol_state.error": "{{ mix red background 40% }}",
    "user_interface.wcol_state.warning": "{{ mix yellow background 40% }}",
    "user_interface.wcol_state.info": "{{ mix blue background 40% }}",
    "user_interface.wcol_state.success": "{{ mix green background 40% }}",
    "user_interface.wcol_state.inner_anim": "{{ green }}",
    "user_interface.wcol_state.inner_anim_sel": "{{ bright_green }}",
    "user_interface.wcol_state.inner_key": "{{ yellow }}",
    "user_interface.wcol_state.inner_key_sel": "{{ bright_yellow }}",
    "user_interface.wcol_state.inner_driven": "{{ magenta }}",
    "user_interface.wcol_state.inner_driven_sel": "{{ bright_magenta }}",
    "user_interface.wcol_state.inner_overridden": "{{ cyan }}",
    "user_interface.wcol_state.inner_overridden_sel": "{{ bright_cyan }}",
    "user_interface.wcol_state.inner_changed": "{{ orange }}",
    "user_interface.wcol_state.inner_changed_sel": "{{ mix orange foreground 25% }}",

    "regions.asset_shelf.back": "{{ dark_background }}",
    "regions.asset_shelf.header_back": "{{ darker_background }}",
    "regions.channels.back": "{{ dark_background }}",
    "regions.channels.text": "{{ foreground }}",
    "regions.channels.text_selected": "{{ accent }}",
    "regions.scrubbing.back": "{{ darker_background }}",
    "regions.scrubbing.text": "{{ dark_foreground }}",
    "regions.sidebars.back": "{{ background }}",
    "regions.sidebars.tab_back": "{{ darker_background }}",

    "common.anim.playhead": "{{ accent }}",
    "common.anim.keyframe": "{{ dark_foreground }}",
    "common.anim.keyframe_selected": "{{ yellow }}",
    "common.anim.channels": "{{ mix accent background 50% }}",
    "common.anim.channels_sub": "{{ mix accent background 70% }}",
    "common.anim.channel_selected": "{{ green }}",

    "topbar.space.back": "{{ darker_background }}",
    "topbar.space.header": "{{ darker_background }}",
    "statusbar.space.back": "{{ darker_background }}",
    "statusbar.space.header": "{{ darker_background }}",
    "statusbar.space.text": "{{ dark_foreground }}",
    "statusbar.space.header_text": "{{ dark_foreground }}",

    "view_3d.space.gradients.high_gradient": "{{ background }}",
    "view_3d.space.gradients.gradient": "{{ dark_background }}",
    "view_3d.grid": "{{ mix background foreground 20% }}",
    "view_3d.grid_major": "{{ mix background foreground 20% }}",
    "view_3d.object_selected": "{{ orange }}",
    "view_3d.object_active": "{{ yellow }}",
    "view_3d.vertex_select": "{{ orange }}",
    "view_3d.edge_select": "{{ orange }}",
    "view_3d.edge_mode_select": "{{ yellow }}",
    "view_3d.face_select": "{{ orange }}",
    "view_3d.face_mode_select": "{{ yellow }}",
    "view_3d.bone_pose": "{{ cyan }}",
    "view_3d.bone_pose_active": "{{ bright_cyan }}",

    "node_editor.space.back": "{{ darker_background }}",
    "node_editor.grid": "{{ lighter_background }}",
    "node_editor.node_backdrop": "{{ lighter_background }}",
    "node_editor.node_selected": "{{ orange }}",
    "node_editor.node_active": "{{ bright_foreground }}",
    "node_editor.wire": "{{ darker_background }}",
    "node_editor.wire_inner": "{{ dark_foreground }}",
    "node_editor.input_node": "{{ mix red background 55% }}",
    "node_editor.output_node": "{{ mix magenta background 60% }}",
    "node_editor.shader_node": "{{ mix green background 55% }}",
    "node_editor.texture_node": "{{ mix orange background 55% }}",
    "node_editor.color_node": "{{ mix yellow background 55% }}",
    "node_editor.vector_node": "{{ mix blue background 55% }}",
    "node_editor.converter_node": "{{ mix cyan background 55% }}",
    "node_editor.geometry_node": "{{ mix green background 45% }}",
    "node_editor.group_node": "{{ mix green background 70% }}",

    "text_editor.space.back": "{{ dark_background }}",
    "text_editor.line_numbers": "{{ dark_foreground }}",
    "text_editor.line_numbers_background": "{{ darker_background }}",
    "text_editor.selected_text": "{{ selection }}",
    "text_editor.cursor": "{{ accent }}",
    "text_editor.syntax_builtin": "{{ red }}",
    "text_editor.syntax_symbols": "{{ orange }}",
    "text_editor.syntax_special": "{{ green }}",
    "text_editor.syntax_preprocessor": "{{ magenta }}",
    "text_editor.syntax_reserved": "{{ blue }}",
    "text_editor.syntax_comment": "{{ dark_foreground }}",
    "text_editor.syntax_string": "{{ yellow }}",
    "text_editor.syntax_numbers": "{{ cyan }}",

    "console.space.back": "{{ dark_background }}",
    "console.line_output": "{{ foreground }}",
    "console.line_input": "{{ bright_foreground }}",
    "console.line_info": "{{ green }}",
    "console.line_error": "{{ red }}",
    "console.cursor": "{{ accent }}",
    "console.select": "{{ selection }}",

    "info.space.back": "{{ dark_background }}",
    "info.info_selected": "{{ selection }}",
    "info.info_selected_text": "{{ selection_foreground }}",

    "outliner.selected_highlight": "{{ selection }}",
    "outliner.active": "{{ mix selection accent 30% }}",
    "outliner.selected_object": "{{ orange }}",
    "outliner.active_object": "{{ yellow }}",
    "outliner.match": "{{ green }}",

    "file_browser.selected_file": "{{ selection }}",
    "properties.match": "{{ accent }}",
    "preferences.match": "{{ accent }}",
    "sequence_editor.space.back": "{{ dark_background }}",
    "sequence_editor.selected_strip": "{{ orange }}",
    "sequence_editor.text_strip_cursor": "{{ accent }}"
  }
}
